import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Loader2, Mail, Shield, User } from 'lucide-react'
import toast from 'react-hot-toast'
import { api } from '../../api/client'
import { useAuthStore } from '../../store/authStore'

export default function SignupPage() {
  const navigate = useNavigate(); const { login } = useAuthStore()
  const [form, setForm] = useState({ full_name: '', username: '', email: '', password: '' }); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const update = (name) => (event) => setForm({ ...form, [name]: event.target.value })
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { await api.register(form); const { data } = await api.login({ email: form.email, password: form.password }); login(data); toast.success('Account created'); navigate('/dashboard') } catch (err) { setError(err.response?.data?.detail || 'Could not create the account') } finally { setLoading(false) } }
  return <main className="min-h-screen bg-hero-gradient cyber-grid-bg flex items-center justify-center p-4"><div className="w-full max-w-md"><div className="text-center mb-7"><Shield className="w-11 h-11 p-2.5 rounded-xl bg-neon-blue/10 border border-neon-blue/30 text-neon-blue mx-auto" /><h1 className="mt-3 text-2xl font-bold gradient-text">Create your analyst account</h1><p className="mt-1 text-sm text-slate-500">Access the TrinetraAI security operations workspace</p></div><div className="glass-strong rounded-2xl p-7 border border-cyber-border">{error && <p className="mb-4 rounded-lg border border-threat-critical/30 bg-threat-critical/10 p-3 text-sm text-threat-critical">{error}</p>}<form onSubmit={submit} className="space-y-4"><Input label="Full name" value={form.full_name} onChange={update('full_name')} icon={User} /><Input label="Username" value={form.username} onChange={update('username')} required icon={User} /><Input label="Email" type="email" value={form.email} onChange={update('email')} required icon={Mail} /><Input label="Password" type="password" value={form.password} onChange={update('password')} required minLength="8" icon={Shield} /><button disabled={loading} className="btn-primary w-full rounded-lg py-2.5 flex justify-center items-center gap-2 text-sm font-semibold">{loading && <Loader2 className="w-4 h-4 animate-spin" />}{loading ? 'Creating account…' : 'Create account'}</button></form><p className="mt-5 text-center text-sm text-slate-500">Already registered? <Link to="/login" className="text-neon-blue">Sign in</Link></p></div></div></main>
}
function Input({ label, icon: Icon, required, ...props }) { return <label className="block text-xs uppercase tracking-wider text-slate-400">{label}<span className="relative mt-1 block"><Icon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" /><input {...props} required={required} className="cyber-input w-full rounded-lg py-2.5 pl-9 pr-3 text-sm normal-case tracking-normal" /></span></label> }
