import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useSearchParams } from 'react-router-dom'
import { Search, ShieldAlert, Wifi } from 'lucide-react'
import { api } from '../../api/client'
import { GlassCard, LoadingSpinner, PageHeader, SeverityBadge } from '../../components/ui/GlassCard'
import { formatRelative } from '../../utils/helpers'

export default function ThreatIntelPage() {
  const [params] = useSearchParams()
  const [search, setSearch] = useState(params.get('search') || '')
  const [submittedSearch, setSubmittedSearch] = useState(search)
  useEffect(() => { const value = params.get('search') || ''; setSearch(value); setSubmittedSearch(value) }, [params])
  const techniques = useQuery({ queryKey: ['mitre-techniques', submittedSearch], queryFn: () => api.getMitreTechniques({ search: submittedSearch || undefined }).then((response) => response.data) })
  const cves = useQuery({ queryKey: ['cves', submittedSearch], queryFn: () => api.getCVEs({ search: submittedSearch || undefined, min_cvss: 0 }).then((response) => response.data) })
  const feeds = useQuery({ queryKey: ['threat-feeds'], queryFn: () => api.getThreatFeeds().then((response) => response.data) })
  if (techniques.isLoading || cves.isLoading || feeds.isLoading) return <div className="h-full flex justify-center items-center"><LoadingSpinner size="lg" /></div>
  return <div><PageHeader title="Threat Intelligence" subtitle="MITRE ATT&CK techniques, known vulnerabilities, and simulated feed indicators" icon={ShieldAlert} /><form onSubmit={(event) => { event.preventDefault(); setSubmittedSearch(search.trim()) }} className="relative max-w-xl mb-5"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search technique ID, CVE, or description" className="cyber-input w-full rounded-lg py-2.5 pl-9 pr-3 text-sm" /></form><div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><GlassCard hover={false}><h2 className="font-semibold text-white">MITRE ATT&CK techniques</h2><div className="mt-4 space-y-3">{(techniques.data?.techniques || []).map((technique) => <div key={technique.id} className="rounded-lg border border-cyber-border/50 p-3"><div className="flex justify-between gap-3"><p className="font-mono text-sm text-neon-cyan">{technique.id}</p><SeverityBadge severity={technique.severity} /></div><p className="mt-1 text-sm text-slate-200">{technique.name}</p><p className="mt-1 text-xs text-slate-500">{technique.tactic}</p></div>)}{!techniques.data?.techniques?.length && <p className="text-sm text-slate-500">No techniques found.</p>}</div></GlassCard><GlassCard hover={false}><h2 className="font-semibold text-white">Vulnerabilities</h2><div className="mt-4 space-y-3">{(cves.data?.cves || []).map((cve) => <div key={cve.cve_id} className="rounded-lg border border-cyber-border/50 p-3"><div className="flex justify-between gap-3"><p className="font-mono text-sm text-neon-purple">{cve.cve_id}</p><span className="text-xs text-threat-high">CVSS {cve.cvss_score}</span></div><p className="mt-1 text-sm text-slate-200">{cve.description}</p><p className="mt-1 text-xs text-slate-500">Affected: {cve.affected} · exploit {cve.exploit_available ? 'available' : 'not known'}</p></div>)}{!cves.data?.cves?.length && <p className="text-sm text-slate-500">No CVEs found.</p>}</div></GlassCard></div><GlassCard hover={false} className="mt-5"><div className="flex gap-2 items-center"><Wifi className="w-4 h-4 text-neon-green" /><h2 className="font-semibold text-white">Threat feeds</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4">{(feeds.data?.feeds || []).map((feed) => <div key={`${feed.feed_name}-${feed.value}`} className="rounded-lg border border-cyber-border/50 p-3"><p className="text-xs text-slate-500">{feed.feed_name}</p><p className="font-mono text-sm text-neon-cyan mt-2 break-all">{feed.value}</p><p className="text-sm text-slate-300 mt-2">{feed.threat_type}</p><p className="text-xs text-slate-500 mt-2">Confidence {Math.round(feed.confidence * 100)}% · {formatRelative(feed.last_seen)}</p></div>)}</div></GlassCard></div>
}
