import { Link } from 'react-router-dom'
import { CheckCircle2, ShieldCheck, TriangleAlert } from 'lucide-react'
import { useInvestigationResources } from '../../hooks/useInvestigationResources'
import { GlassCard, LoadingSpinner, PageHeader, StatusBadge } from '../../components/ui/GlassCard'
import { formatDate } from '../../utils/helpers'

export default function VerificationCenterPage() {
  const { items: reports, isLoading } = useInvestigationResources('verifications')
  if (isLoading) return <div className="h-full flex items-center justify-center"><LoadingSpinner size="lg" /></div>
  const effective = reports.filter((report) => report.status === 'effective').length
  return <div><PageHeader title="Verification Center" subtitle="Validate containment effectiveness and environment stability" icon={CheckCircle2} /><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-5"><Summary label="Reports" value={reports.length} icon={CheckCircle2} color="text-neon-blue" /><Summary label="Effective" value={effective} icon={ShieldCheck} color="text-neon-green" /><Summary label="Need review" value={reports.filter((report) => report.status !== 'effective').length} icon={TriangleAlert} color="text-threat-high" /></div><div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{reports.length ? reports.sort((a, b) => new Date(b.created_at) - new Date(a.created_at)).map((report) => <GlassCard key={report.id} hover={false}><div className="flex justify-between gap-3"><div><p className="font-mono text-xs text-neon-cyan">{report.investigation.investigation_id}</p><p className="mt-2 text-sm text-slate-400">Generated {formatDate(report.created_at)}</p></div><StatusBadge status={report.status} /></div><div className="grid grid-cols-3 gap-2 mt-4 text-center text-xs"><Check label="Neutralized" yes={report.attack_neutralized} /><Check label="Contained" yes={report.threat_contained} /><Check label="Stable" yes={report.environment_stable} /></div><p className="mt-4 text-sm text-slate-300">Effectiveness score: {Math.round((report.effectiveness_score || 0) * 100)}%</p>{(report.recommendations || []).length > 0 && <ul className="mt-3 space-y-1 text-xs text-slate-400 list-disc pl-4">{report.recommendations.map((recommendation, index) => <li key={index}>{recommendation}</li>)}</ul>}<Link to={`/investigations/${report.investigation.investigation_id}`} className="mt-4 inline-block text-xs text-neon-blue">Open investigation</Link></GlassCard>) : <GlassCard hover={false} className="col-span-full text-center py-12"><p className="text-slate-500">Verification reports will appear after response actions run.</p></GlassCard>}</div></div>
}
function Summary({ label, value, icon: Icon, color }) { return <GlassCard hover={false} className="p-4"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-2 text-2xl font-semibold ${color}`}>{value}</p></div><Icon className={`w-5 h-5 ${color}`} /></div></GlassCard> }
function Check({ label, yes }) { return <div className="rounded-lg bg-cyber-surface border border-cyber-border/50 p-2"><p className={yes ? 'text-neon-green' : 'text-threat-critical'}>{yes ? 'Yes' : 'No'}</p><p className="mt-1 text-slate-500">{label}</p></div> }
