import { Link } from 'react-router-dom'
import { ShieldCheck, Undo2, Zap } from 'lucide-react'
import { useInvestigationResources } from '../../hooks/useInvestigationResources'
import { GlassCard, LoadingSpinner, PageHeader, StatusBadge } from '../../components/ui/GlassCard'
import { formatDate } from '../../utils/helpers'

export default function ResponseCenterPage() {
  const { items: responses, isLoading } = useInvestigationResources('responses')
  if (isLoading) return <div className="h-full flex items-center justify-center"><LoadingSpinner size="lg" /></div>
  const complete = responses.filter((response) => response.status === 'completed').length
  return <div><PageHeader title="Response Center" subtitle="Simulated containment and remediation actions generated by investigations" icon={Zap} /><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-5"><Stat label="Recorded actions" value={responses.length} icon={Zap} color="text-neon-purple" /><Stat label="Completed" value={complete} icon={ShieldCheck} color="text-neon-green" /><Stat label="Rollback capable" value={responses.filter((response) => response.can_rollback).length} icon={Undo2} color="text-neon-cyan" /></div><div className="space-y-3">{responses.length ? responses.sort((a, b) => new Date(b.executed_at) - new Date(a.executed_at)).map((response) => <GlassCard key={response.id} hover={false}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold capitalize text-white">{response.action?.replace(/_/g, ' ')}</p><p className="mt-1 text-sm text-slate-400">Target: {response.target || 'Not specified'}</p></div><StatusBadge status={response.status} /></div><p className="mt-3 text-sm text-slate-300">{response.reasoning || 'No response reasoning was recorded.'}</p><div className="mt-4 flex justify-between gap-3 text-xs text-slate-500"><span>Executed {formatDate(response.executed_at)}</span><Link to={`/investigations/${response.investigation.investigation_id}`} className="text-neon-blue">{response.investigation.investigation_id}</Link></div></GlassCard>) : <NoItems />}</div></div>
}
function Stat({ label, value, icon: Icon, color }) { return <GlassCard hover={false} className="p-4"><div className="flex justify-between"><div><p className="text-[10px] text-slate-500 uppercase tracking-wider">{label}</p><p className={`mt-2 text-2xl font-semibold ${color}`}>{value}</p></div><Icon className={`w-5 h-5 ${color}`} /></div></GlassCard> }
function NoItems() { return <GlassCard hover={false} className="text-center py-12"><p className="text-slate-500">Response actions will appear when an investigation reaches its response stage.</p></GlassCard> }
